export default (name, key) => variants[name][key];

const variants = {
  brand: {
    ABARTH: "Abarth",
    ALFA_ROMEO: "Alfa Romeo",
    ASTON_MARTIN: "Aston Martin",
    AUDI: "Audi",
    BENTLEY: "Bentley",
    BMW: "BMW",
    CADILLAC: "Cadillac",
    CHEVROLET: "Chevrolet",
    CHRYSLER: "Chrysler",
    CITROEN: "Citroen",
    DE_LOREAN: "De Lorean",
    DODGE: "Dodge",
    FERRARI: "Ferrari",
    FIAT: "Fiat",
    FORD: "Ford",
    HONDA: "Honda",
    HUMMER: "Hummer",
    JAGUAR: "Jaguar",
    JEEP: "Jeep",
    KIA: "Kia",
    LADA: "Lada",
    LAMBORGHINI: "Lamborghini",
    LANCIA: "Lancia",
    LEXUS: "Lexus",
    MASERATI: "Maserati",
    MAYBACH: "Maybach",
    MAZDA: "Mazda",
    MERCEDES_BENZ: "Mercedes Benz",
    MERCURY: "Mercury",
    MITSUBISHI: "Mitsubishi",
    MOSKWICZ: "Moskwicz",
    NISSAN: "Nissan",
    OLDSMOBILE: "Oldsmobile",
    OPEL: "Opel",
    PEUGEOT: "Peugeot",
    PLYMOUTH: "Plymouth",
    POLONEZ: "Polonez",
    PONTIAC: "Pontiac",
    PORSCHE: "Porsche",
    RENAULT: "Renault",
    ROLLS_ROYCE: "Rolls Royce",
    ROVER: "Rover",
    SAAB: "Saab",
    SKODA: "Skoda",
    SYRENA: "Syrena",
    TOYOTA: "Toyota",
    TRABANT: "Trabant",
    TRIUMPH: "Triumph",
    VOLKSWAGEN: "Volkswagen",
    VOLVO: "Volvo",
    WARSZAWA: "Warszawa",
    WARTBURG: "Wartburg",
    WOLGA: "Wołga",
    ZAPOROZEC: "Zaporożec",
    ZUK: "Żuk",
    OTHER: "Inne"
  },
  fuelType: {
    BENZYNA: "Benzyna",
    BENZYNA_LPG: "Benzyna + LPG",
    BENZYNA_CNG: "Benzyna + CNG",
    DIESEL: "Olej napędowy",
    HYBRYDA: "Hybryda",
    ELEKTRYCZNY: "Elektryczny",
    OTHER: "Inny"
  },
  transmission: {
    MANUAL: "Manualna",
    AUTOMATIC_CLASSIC: "Automatyczna klasyczna",
    AUTOMATIC_SHIFTLESS: "Automatyczna bezstopniowa",
    AUTOMATIC_SEMI: "Półautomatyczna",
    AUTOMATIC_DUAL_CLUTCH: "Automatyczna dwusprzęgłowa"
  },
  drive: {
    FRONT_WHEEL_DRIVE: "Na przednie koła",
    REAR_WHEEL_DRIVE: "Na tylne koła",
    FOUR_WHEEL_DRIVE_AUTOMATIC: "4x4 dołączany automatycznie",
    FOUR_WHEEL_DRIVE_MANUAL: "4x4 dołączany ręcznie",
    FOUR_WHEEL_DRIVE_FIXED: "4x4 stały"
  },
  color: {
    WHITE: "Biały",
    BEIGE: "Beżowy",
    MAROON: "Bordowy",
    BROWN: "Brązowy",
    BLACK: "Czarny",
    RED: "Czerwony",
    VIOLET: "Fioletowy",
    BLUE: "Niebieski",
    SILVER: "Srebrny",
    GRAY: "Szary",
    GREEN: "Zielony",
    GOLD: "Złoty",
    YELLOW: "Żółty",
    OTHER: "Inny"
  },
  additionalAccessories_Appereance: {
    ALLOY_WHEELS: "Ameliniowe felgi",
    TINTED_WINDOWS: "Przyciemniane szyby",
    METALLIC_PAINT: "Lakier metalik",
    MATTE_PAINT: "Lakier matowy",
    PEARL_PAINT: "Lakier perłowy"
  },
  additionalAccessories_Safety: {
    ABS: "ABS",
    ESP: "ESP",
    ASR: "ASR",
    CENTRAL_LOCKING: "Centralny zamek",
    IMMOBILIZER: "Immobilizer",
    ALARM: "Alarm",
    DRIVER_AIRBAG: "Poduszka powietrzna kierowcy",
    PASSENGER_AIRBAG: "Poduszka powietrzna pasażera",
    SIDE_FRONT_AIRBAGS: "Boczne poduszki powietrzne z przodu",
    SIDE_BACK_AIRBAGS: "Boczne poduszki powietrzne z tyłu"
  },
  additionalAccessories_Comfort_Driver: {
    POWER_STEERING: "Wspomaganie kierownicy",
    HEATED_STEERING_WHEEL: "Podgrzewana kierownica",
    MULTIFUNCTION_STEERING_WHEEL: "Wielofunkcyjna kierownica",
    PADDLE_SHIFTERS: "Łopatki zmiany biegów",
    ACTIVE_SUSPENSION: "Aktywne zawieszenie",
    REGULATED_SUSPENSION: "Regulowane zawieszenie",
    ELECTRIC_MIRRORS: "Elektrycznie ustawiane lusterka",
    HEATED_MIRRORS: "Podgrzewane lusterka",
    ON_BOARD_COMPUTER: "Komputer pokładowy",
    PARKING_SENSOR_FRONT: "Czujniki parkowania z przodu",
    PARKING_SENSOR_BACK: "Czujniki parkowania z tyłu",
    REVERSE_CAMERA: "Kamera cofania",
    RAIN_SENSOR: "Czujnik deszczu",
    CRUISE_CONTROL: "Tempomat",
    FOG_LIGHTS: "Światła przeciwmgielne",
    LED_LIGHTS: "Światła ledowe",
    XENON_LIGHTS: "Światła Xenonowe",
    GPS_NAVIGATION: "Nawigacja GPS",
    SPEED_LIMITER: "Ogranicznik prędkości"
  },
  additionalAccessories_Comfort_Passenger: {
    ELECTRIC_FRONT_WINDOWS: "Elektryczne szyby przednie",
    ELECTRIC_BACK_WINDOWS: "Elektryczne szyby tylne",
    FACTORY_RADIO: "Radio fabryczne",
    NON_STANDARD_RADIO: "Radio niefabryczne",
    AUX: "Gniazdo AUX",
    MP3: "Gniazdo MP3",
    CD: "CD",
    CD_CHANGER: "Zmieniarka CD",
    DVD_PLAYER: "Odtwarzacz DVD",
    TV_TUNER: "Tuner TV",
    LEATHER_UPHOLSTERY: "Tapicerka skórzana",
    VELOR_UPHOLSTERY: "Tapicerka welurowa",
    ELECTRIC_ADJUSTABLE_FRONT_SEATS: "Elektrycznie ustawiane przednie fotele",
    ELECTRIC_ADJUSTABLE_BACK_SEATS: "Elektrycznie ustawiane tylne fotele",
    HEATED_FRONT_SEATS: "Podgrzewane przednie siedzenia",
    HEATED_BACK_SEATS: "Podgrzewane tylne siedzenia",
    PANORAMIC_ROOF: "Dach panoramiczny",
    SUNROOF: "Szyberdach",
    ROOF_RACK: "Relingi dachowe",
    PARKING_HEATER: "Ogrzewanie postojowe",
    HEATED_FRONT_WINDSCREEN: "Podgrzewana przednia szyba",
    AIR_CONDITIONING_AUTOMATIC: "Klimatyzacja automatyczna",
    AIR_CONDITIONING_DUAL_ZONE: "Klimatyzacja 2-strefowa",
    AIR_CONDITIONING_THREE_ZONE: "Klimatyzacja 3-strefowa",
    AIR_CONDITIONING_FOUR_ZONE: "Klimatyzacja 4-strefowa",
    AIR_CONDITIONING_MANUAL: "Klimatyzacja manualna"
  },
  attributesNames: {
    price: "Cena",
    localization: "Lokalizacja",
    avatar: "Miniaturka",
    photos: "Galeria zdjęć",
    segment: "Segment",
    brand: "Marka",
    model: "Model",
    version: "Wersja",
    mileage: "Przebieg",
    productionYear: "Rok produkcji",
    fuelType: "Rodzaj paliwa",
    engineSize: "Pojemność skokowa",
    power: "Moc",
    torque: "Moment obrotowy",
    transmission: "Rodzaj skrzyni biegów",
    drive: "Rodzaj układu napędowego",
    additionalAccessories_Safety: "Dodatkowe wyposażenie - bezpieczeństwo",
    additionalAccessories_Comfort_Passenger:
      "Dodatkowe wyposażenie - komfort pasażerów",
    additionalAccessories_Comfort_Driver:
      "Dodatkowe wyposażenie - komfort kierowcy",
    additionalAccessories_Appereance: "Dodatkowe wyposażenie - wygląd",
    damaged: "Uszkodzony",
    accidentFree: "Bezwypadkowy",
    firstOwner: "Pierwszy właściciel",
    registeredInPoland: "Zarejestrowany w Polsce",
    registeredAsAntiqueCar: "Zarejestrowany jako zabytek",
    hasVIN: "Posiada VIN",
    tuning: "Tuning",
    hasParticulateFilter: "Posiada filtr cząstek stałych",
    steeringWheelOnTheRight: "Kierownica po prawej stronie",
    color: "Kolor"
  }
};
