export default (variant, enumName, key) => variants[variant][enumName][key];

const variants = {
  Car: {
    brand: {
      ABARTH: "Abarth",
      ALFA_ROMEO: "Alfa Romeo",
      ASTON_MARTIN: "Aston Martin",
      AUDI: "Audi",
      BENTLEY: "Bentley",
      BMW: "BMW",
      CADILLAC: "Cadillac",
      CHEVROLET: "Chevrolet",
      CHRYSLER: "Chrysler",
      CITROEN: "Citroen",
      DE_LOREAN: "De Lorean",
      DODGE: "Dodge",
      FERRARI: "Ferrari",
      FIAT: "Fiat",
      FORD: "Ford",
      HONDA: "Honda",
      HUMMER: "Hummer",
      JAGUAR: "Jaguar",
      JEEP: "Jeep",
      KIA: "Kia",
      LADA: "Lada",
      LAMBORGHINI: "Lamborghini",
      LANCIA: "Lancia",
      LEXUS: "Lexus",
      MASERATI: "Maserati",
      MAYBACH: "Maybach",
      MAZDA: "Mazda",
      MERCEDES_BENZ: "Mercedes Benz",
      MERCURY: "Mercury",
      MITSUBISHI: "Mitsubishi",
      MOSKWICZ: "Moskwicz",
      NISSAN: "Nissan",
      OLDSMOBILE: "Oldsmobile",
      OPEL: "Opel",
      PEUGEOT: "Peugeot",
      PLYMOUTH: "Plymouth",
      POLONEZ: "Polonez",
      PONTIAC: "Pontiac",
      PORSCHE: "Porsche",
      RENAULT: "Renault",
      ROLLS_ROYCE: "Rolls Royce",
      ROVER: "Rover",
      SAAB: "Saab",
      SKODA: "Skoda",
      SYRENA: "Syrena",
      TOYOTA: "Toyota",
      TRABANT: "Trabant",
      TRIUMPH: "Triumph",
      VOLKSWAGEN: "Volkswagen",
      VOLVO: "Volvo",
      WARSZAWA: "Warszawa",
      WARTBURG: "Wartburg",
      WOLGA: "Wołga",
      ZAPOROZEC: "Zaporożec",
      ZUK: "Żuk",
      OTHER: "Inne"
    },
    fuelType: {
      BENZYNA: "Benzyna",
      BENZYNA_LPG: "Benzyna + LPG",
      BENZYNA_CNG: "Benzyna + CNG",
      DIESEL: "Diesel",
      HYBRYDA: "Hybryda",
      ELEKTRYCZNY: "Elektryczny",
      INNY: "Inny"
    }
  },
  Post: {}
};
