export default (enumName, key) => variants[enumName][key];

const variants = {
  brand: {
    ABARTH: "Abarth",
    ALFA_ROMEO: "Alfa Romeo",
    ASTON_MARTIN: "Aston Martin",
    AUDI: "Audi",
    BENTLEY: "Bentley",
    BMW: "BMW",
    CADILLAC: "Cadillac",
    CHEVROLET: "Chevrolet",
    CHRYSLER: "Chrysler",
    CITROEN: "Citroen",
    DE_LOREAN: "De Lorean",
    DODGE: "Dodge",
    FERRARI: "Ferrari",
    FIAT: "Fiat",
    FORD: "Ford",
    HONDA: "Honda",
    HUMMER: "Hummer",
    JAGUAR: "Jaguar",
    JEEP: "Jeep",
    KIA: "Kia",
    LADA: "Lada",
    LAMBORGHINI: "Lamborghini",
    LANCIA: "Lancia",
    LEXUS: "Lexus",
    MASERATI: "Maserati",
    MAYBACH: "Maybach",
    MAZDA: "Mazda",
    MERCEDES_BENZ: "Mercedes Benz",
    MERCURY: "Mercury",
    MITSUBISHI: "Mitsubishi",
    MOSKWICZ: "Moskwicz",
    NISSAN: "Nissan",
    OLDSMOBILE: "Oldsmobile",
    OPEL: "Opel",
    PEUGEOT: "Peugeot",
    PLYMOUTH: "Plymouth",
    POLONEZ: "Polonez",
    PONTIAC: "Pontiac",
    PORSCHE: "Porsche",
    RENAULT: "Renault",
    ROLLS_ROYCE: "Rolls Royce",
    ROVER: "Rover",
    SAAB: "Saab",
    SKODA: "Skoda",
    SYRENA: "Syrena",
    TOYOTA: "Toyota",
    TRABANT: "Trabant",
    TRIUMPH: "Triumph",
    VOLKSWAGEN: "Volkswagen",
    VOLVO: "Volvo",
    WARSZAWA: "Warszawa",
    WARTBURG: "Wartburg",
    WOLGA: "Wołga",
    ZAPOROZEC: "Zaporożec",
    ZUK: "Żuk",
    OTHER: "Inne"
  },
  fuelType: {
    BENZYNA: "Benzyna",
    BENZYNA_LPG: "Benzyna + LPG",
    BENZYNA_CNG: "Benzyna + CNG",
    DIESEL: "Olej napędowy",
    HYBRYDA: "Hybryda",
    ELEKTRYCZNY: "Elektryczny",
    INNY: "Inny"
  },
  transmission: {
    MANUAL: "Manualna",
    AUTOMATIC_CLASSIC: "Automatyczna klasyczna",
    AUTOMATIC_SHIFTLESS: "Automatyczna bezstopniowa",
    AUTOMATIC_SEMI: "Półautomatyczna",
    AUTOMATIC_DUAL_CLUTCH: "Automatyczna dwusprzęgłowa"
  },
  drive: {
    FRONT_WHEEL_DRIVE: "Na przednie koła",
    REAR_WHEEL_DRIVE: "Na tylne koła",
    FOUR_WHEEL_DRIVE_AUTOMATIC: "4x4 dołączany automatycznie",
    FOUR_WHEEL_DRIVE_MANUAL: "4x4 dołączany ręcznie",
    FOUR_WHEEL_DRIVE_FIXED: "4x4 stały"
  },
  color: {
    WHITE: "Biały",
    BEIGE: "Beżowy",
    MAROON: "Bordowy",
    BROWN: "Brązowy",
    BLACK: "Czarny",
    RED: "Czerwony",
    VIOLET: "Fioletowy",
    BLUE: "Niebieski",
    SILVER: "Srebrny",
    GRAY: "Szary",
    GREEN: "Zielony",
    GOLD: "Złoty",
    YELLOW: "Żółty",
    OTHER: "Inny"
  },
  AdditionalAccessory_Appereance: {
    ALLOY_WHEELS: "Ameliniowe felgi",
    TINTED_WINDOWS: "Przyciemniane szyby",
    METALLIC_PAINT: "Lakier metalik",
    MATTE_PAINT: "Lakier matowy",
    PEARL_PAINT: "Lakier perłowy"
  }
};
